USE [master]
GO

/****** Object:  Database [ComicBooks]    ******/
CREATE DATABASE [ComicBooks] ON  PRIMARY 
( NAME = N'ComicBooks', FILENAME = N'C:\ComicBooks.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ComicBooks_log', FILENAME = N'C:\ComicBooks_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ComicBooks] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ComicBooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ComicBooks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ComicBooks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ComicBooks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ComicBooks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ComicBooks] SET ARITHABORT OFF 
GO

ALTER DATABASE [ComicBooks] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ComicBooks] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ComicBooks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ComicBooks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ComicBooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ComicBooks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ComicBooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ComicBooks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ComicBooks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ComicBooks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ComicBooks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ComicBooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ComicBooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ComicBooks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ComicBooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ComicBooks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ComicBooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ComicBooks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ComicBooks] SET  READ_WRITE 
GO

ALTER DATABASE [ComicBooks] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ComicBooks] SET  MULTI_USER 
GO

ALTER DATABASE [ComicBooks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ComicBooks] SET DB_CHAINING OFF 
GO


